// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOtXwgPjxe_gBNj4K7AsE_YtDU0tcAURc',
    appId: '1:350315201940:android:fcd7c285ab4087a1debb81',
    messagingSenderId: '350315201940',
    projectId: 'project-santa-nkg',
    storageBucket: 'project-santa-nkg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABWWToy8beHs3F-8qZ38PjHRe2Y3pBlyA',
    appId: '1:350315201940:ios:83c6b969533260d9debb81',
    messagingSenderId: '350315201940',
    projectId: 'project-santa-nkg',
    storageBucket: 'project-santa-nkg.firebasestorage.app',
    iosBundleId: 'com.example.projectSanta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDckOREeo5uBN-2vHTpO-FV4uYTvqhZ2TM',
    appId: '1:350315201940:web:1b22948de7d35360debb81',
    messagingSenderId: '350315201940',
    projectId: 'project-santa-nkg',
    authDomain: 'project-santa-nkg.firebaseapp.com',
    storageBucket: 'project-santa-nkg.firebasestorage.app',
  );

}